# Generated by Django 2.2.16 on 2020-09-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dating_location', models.CharField(max_length=32)),
                ('dating_gender', models.FloatField(default=0)),
                ('min_distance', models.IntegerField(max_length=100)),
                ('max_distance', models.IntegerField(max_length=100)),
                ('min_dating_age', models.IntegerField(max_length=100)),
                ('max_dating_age', models.IntegerField(max_length=100)),
                ('vibration', models.FloatField(default=0)),
                ('only_matched', models.FloatField(default=0)),
                ('auto_play', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
