# Generated by Django 2.2.16 on 2020-09-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='auto_play',
            field=models.BooleanField(verbose_name='⾃动播放视频'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_gender',
            field=models.CharField(choices=[('male', '男性'), ('female', '女性')], max_length=10, verbose_name='匹配的性别'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dating_location',
            field=models.CharField(choices=[('北京', '北京'), ('上海', '上海'), ('深圳', '深圳'), ('成都', '成都'), ('西安', '西安'), ('武汉', '武汉'), ('沈阳', '沈阳')], max_length=10, verbose_name='⽬标城市'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(max_length=100, verbose_name='最⼤交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='max_distance',
            field=models.FloatField(max_length=100, verbose_name='最⼤查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(max_length=100, verbose_name='最⼩交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_distance',
            field=models.FloatField(max_length=100, verbose_name='最⼩查找范围'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='only_matched',
            field=models.BooleanField(verbose_name='不让陌⽣⼈看我的相册'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vibration',
            field=models.BooleanField(verbose_name='开启震动'),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
