# Generated by Django 2.2.16 on 2020-09-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200923_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='max_dating_age',
            field=models.IntegerField(verbose_name='最⼤交友年龄'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='min_dating_age',
            field=models.IntegerField(verbose_name='最⼩交友年龄'),
        ),
    ]
